import numpy as np
import csv
import sys


# ( 4.0 + 2.0 i ) => 4.0+2.0j
def parse_complex(s):
    pass
    # s = s.strip("() ").replace(" ", "")
    # s = s.replace("i", "j")
    # try:
    #     return complex(s)
    # except ValueError:
    #     raise ValueError(f"Could not parse complex number: '{s}'")


# The following same_elements function was generated by Claude Code Sonnet 5 on 
# the 04/09/2026 for testing purposes only.
def same_elements(a: np.ndarray, b: np.ndarray, tol: float = 1e-8) -> bool:
    """
    Return True if complex arrays a and b contain the same elements,
    regardless of order, treating values within `tol` as equal.
    Pure NumPy (no scipy) — uses greedy nearest-neighbor matching.
    """
    a = np.asarray(a).ravel()
    b = np.asarray(b).ravel()

    if a.size != b.size:
        return False
    if a.size == 0:
        return True

    # Pairwise distance matrix
    cost = np.abs(a[:, None] - b[None, :])
    n = cost.shape[0]

    used_b = np.zeros(n, dtype=bool)

    # Greedily match each element of a to its closest unused element of b,
    # processing the globally smallest distances first for stability.
    flat_order = np.argsort(cost, axis=None)
    matched_a = np.zeros(n, dtype=bool)

    for idx in flat_order:
        i, j = divmod(idx, n)
        if matched_a[i] or used_b[j]:
            continue
        if cost[i, j] > tol:
            # Remaining distances only get bigger from here in sorted order,
            # but other rows/cols might still need this... so just record failure.
            return False
        matched_a[i] = True
        used_b[j] = True
        if matched_a.all():
            return True

    return matched_a.all()

if __name__ == "__main__":
    input = list(csv.DictReader(sys.stdin))

    input_arr = np.array(
                    [float(x[" Input-Real"]) + (1j * float(x[" Input-Imag"])) for x in input], 
                    dtype=complex
                )
    CDFT_arr = np.array(
                    [float(x[" DFT-Real"]) + (1j * float(x[" DFT-Imag"])) for x in input], 
                    dtype=complex
                )
    CFFT_arr = np.array(
                    [float(x[" FFT-Real"]) + (1j * float(x[" FFT-Imag"])) for x in input], 
                    dtype=complex
                )

    NPFFT_applied = np.fft.fft(input_arr)

    results = np.stack([CDFT_arr, CFFT_arr, NPFFT_applied], axis=1)

    CDFT_CFFT_Real_Diff = 0
    CDFT_CFFT_Imag_Diff = 0
    CDFT_PFFT_Real_Diff = 0
    CDFT_PFFT_Imag_Diff = 0
    CFFT_PFFT_Real_Diff = 0
    CFFT_PFFT_Imag_Diff = 0
    count=0

    for row in results:
        CDFT_CFFT_Real_Diff += abs(np.real(row[0]) - np.real(row[1]))
        CDFT_CFFT_Imag_Diff += abs(np.imag(row[0]) - np.imag(row[1]))
    
        CDFT_PFFT_Real_Diff += abs(np.real(row[0]) - np.real(row[2]))
        CDFT_PFFT_Imag_Diff += abs(np.imag(row[0]) - np.imag(row[2]))

        CFFT_PFFT_Real_Diff += abs(np.real(row[1]) - np.real(row[2]))
        CFFT_PFFT_Imag_Diff += abs(np.imag(row[1]) - np.imag(row[2]))

        count += 1

    # print("GIVEN_DFT_&FFT_Real_Diff: ", CDFT_CFFT_Real_Diff / count)
    # print("GIVEN_DFT_&FFT_Imag_Diff: ", CDFT_CFFT_Imag_Diff / count)
    print("Agda DFT, Python FFT Real: ", CDFT_PFFT_Real_Diff / count)
    print("Agda DFT, Python FFT Imag: ", CDFT_PFFT_Imag_Diff / count)
    print("Agda FFT, Python FFT Real: ", CFFT_PFFT_Real_Diff / count)
    print("Agda FFT, Python FFT Imag: ", CFFT_PFFT_Imag_Diff / count)

    if (same_elements(CDFT_arr, NPFFT_applied)):
        print("Agda DFT contains same elements as Python FFT")
    else:
        print("Agda DFT does not contain the same elements as Python FFT")
        

    if (same_elements(CFFT_arr, NPFFT_applied)):
        print("Agda FFT contains same elements as Python FFT")
    else:
        print("Agda FFT does not contain the same elements as Python FFT")


    


    


    #if len(sys.argv) < 2:
    #    print("Input csv string not provided")
    #    sys.exit(1)

    #try:
    #    cli_input = sys.argv[1].split(",");
    #    print(cli_input)

        # input_arr = [parse_complex(x) for x in cli_input.split(",")]

        # np_arr = np.array(input_arr, dtype=complex)

        # FFT_applied = np.fft.fft(np_arr)

        # print("Python FFT Result: [", end="")
        # print(FFT_applied[0], end="")

        # for x in FFT_applied[1:]:
        #     print(", ", x, sep="", end="")

        # print("]")

    #except ValueError:
    #    print("Invalid input form")

